export const countries = [
    { code: "AU", name: "australia" },
    { code: "AT", name: "austria" },
    { code: "BE", name: "belgium" },
    { code: "BR", name: "brazil" },
    { code: "BG", name: "bulgaria" },
    { code: "CM", name: "cameroon" },
    { code: "CA", name: "canada" },
    { code: "CO", name: "colombia" },
    { code: "CY", name: "cyprus" },
    { code: "CZ", name: "czechia" },
    { code: "DK", name: "denmark" },
    { code: "FR", name: "france" },
    { code: "DE", name: "germany" },
    { code: "GI", name: "gibraltar" },
    { code: "GR", name: "greece" },
    { code: "IN", name: "india" },
    { code: "IE", name: "ireland" },
    { code: "IT", name: "italy" },
    { code: "LT", name: "lithuania" },
    { code: "MT", name: "malta" },
    { code: "NL", name: "netherlands" },
    { code: "PL", name: "poland" },
    { code: "RS", name: "serbia" },
    { code: "ES", name: "spain" },
    { code: "CH", name: "switzerland" },
    { code: "UA", name: "ukraine" },
    { code: "GB", name: "united kingdom" },
    { code: "US", name: "united states" }
].sort((a, b) => a.name.localeCompare(b.name));