export const skillsList = [
    "Social Media",
    "Digital Marketing",
    "Event Management",
    "Project Management",
    "Sales",
    "Business Development",
    "Communication",
    "Leadership",
    "Analytics",
    "Performance Analysis",
    "Coaching",
    "Sports Science",
    "Strength & Conditioning",
    "Video Analysis",
    "Sponsorship",
    "Sports Marketing",
    "Content Creation",
    "Brand Management",
    "Data Analysis",
    "CRM",
].sort();
